name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install renv
      run: install.packages('renv')
      shell: Rscript {0}

    - name: Restore renv environment
      run: |
        renv::restore()
      shell: Rscript {0}

    - name: Install rsconnect
      run: install.packages('rsconnect')
      shell: Rscript {0}

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        library(rsconnect)
        rsconnect::setAccountInfo(name = Sys.getenv("SHINYAPPS_ACCOUNT"),
                                  token = Sys.getenv("SHINYAPPS_TOKEN"),
                                  secret = Sys.getenv("SHINYAPPS_SECRET"))
        rsconnect::deployApp(appName = "BaoGame", 
                             forceUpdate = TRUE)
      shell: Rscript {0}
